# Site settings
author: Jeshua Hicks 
title: Amazing Programming
header-img: img/home-bg.png
email: jhicks7884@outlook.com
copyright_name: Jeshua Hicks 
description: > # this means to ignore newlines until "baseurl:"
  Learning to program
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jhicks7884

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
